### PR TITLE
Use Elasticsearch 7.17.6

### PR DESCRIPTION
**Pull request by AronNovak**
image

For now, a minor bump.

### CODE REVIEW

**Review by rfay — APPROVED** [review]
Looks fine to me. I wish they'd do their tags like all the other official images so we could just use a tag of `7.17` or even `7`.

**Comment by AronNovak** [comment]
@rfay But what's actually the benefit of that? For me it's more expressive what's the exact version I refer to, and we don't break things accidentally.

**Comment by rfay** [comment]
Well, it doesn't matter much because they don't do it. But when things like horrible security failures like Log4J come along, they can just be updated in the image and not in every single project that refers to the image.

**Comment by rfay** [comment]
Thanks so much for maintaining this!

**Pull request merged**
