### PR TITLE
Bump ES to 8.1.1

### PR DESCRIPTION
**Pull request by AronNovak**
https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-8.1.1.html

### CODE REVIEW

**Comment by AronNovak** [comment]
@rfay Do I need to do anything differently workflow-wise due to the fact that this repo is generated from https://github.com/drud/ddev-addon-template?

I am testing the compatibility with at least the Drupal connectivity module at https://github.com/Gizra/drupal-starter/pull/244

**Comment by rfay** [comment]
The ddev-addon-template was just a GitHub starter, it's completely irrelevant now.

**Comment by rfay** [comment]
Don't know why the tests are so completely blown out by this. Does it work for you locally? `bats tests`

I usually just run the things in `bats tests` manually one by one to figure out what's going on.

**Comment by rfay** [comment]
I took a look - It seems that Elasticsearch 8.1.1 uses an https self-signed-cert server on port 9200, so the healthcheck can't succeed in connecting (it's expecting http). 
* Dockerhub: https://hub.docker.com/_/elasticsearch
* 8.1.1 Dockerfile: https://github.com/docker-library/elasticsearch/blob/70d9beec187b48296fb5cb4ac75d54f91cdc8450/8/Dockerfile
* Github https://github.com/docker-library/elasticsearch

This problem will also mean that as we understand it, 8.1.1 can't be used anyway because of the self-signed https, which neither ddev-router nor the web container will be able to connect to, unless we turn off checking.

Upstream docs may imply that you now need a license/trial: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

Interesting, after adding ES_PORT=9200 and LICENSE=basic I now see http working - it's possible I was confused before.

`{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","ApiKey"]}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","ApiKey"]}},"status":401}`

But this definitely makes things more complicated.

**Comment by AronNovak** [comment]
@rfay ES 8 introduced required authentication by default, that's why my other PR also fails, I will sort that out and can return back to that.
There's a way to reset the password of the `elastic` user, that would be my take:
https://www.elastic.co/guide/en/elasticsearch/reference/current/reset-password.html


But it doesn't accept a specific password, it just auto-generates one, which is suboptimal for our case. That's where I am now.

**Comment by rfay** [comment]
Nice work. The healthcheck will have to be somewhat more sophisticated.

Note that the healthcheck is pretty important because it may take several seconds for elasticsearch to actually be ready to serve, which can cause test failures, etc.

**Comment by AronNovak** [comment]
@rfay At Drupal Starter, now it works with authentication, it's only the matter of env variables:
``
      - ELASTIC_PASSWORD=1234567890123456789
      - ES_PORT=9200
      - LICENSE=basic
```

for instance.

**Comment by rfay** [comment]
Does it just need an improved healthcheck now?

**Comment by AronNovak** [comment]
@rfay Maybe, but the Drupal connector module is not yet ready for ES8, so we likely should wait with this.

**Comment by AronNovak** [comment]
There are various warnings when I use ES 8 locally with Elasticsearch Connector.

**Comment by rfay** [comment]
Closing this for now, I'm sure you'll be back with more when the time comes.

**Pull request closed without merging**
